library(ggraptR)
library(poolSeq)
library(patchwork)
library(dplyr)
library(ggridges)
library(tidyr)
library(viridis)
library(colorspace)
library(gganimate)
library(gifski)
library(av)
library(png)
library(magick)
library(scico)
library(plotrix)
library(ggdensity)
library(ggplot2) # needs to be version ≥ 2.1.0
library(scales)
library(devtools)
library(network)
library(sna)
library(GGally)
library(geomnet)
library(ggnetwork)
library(igraph)
library(ggraph)
library(tidygraph)
library(vcfR)
library(ggplotify)
library(pheatmap)
library(ggbreak)
library(ggimage)
library(rsvg)
library(ggrepel)
library(shadowtext)
dev.off()

seeds <- sample(1:10000, 400) 
Us <- rep(c(2.5e-3, 2.5e-2), each = 200)
as <- rep(c(0.01, 0.005), times = 200)



df <- data.frame(seeds,
                 Us,
                 as)
write.table(df, file = "params.txt", sep=",",  col.names=FALSE, row.names = FALSE)
